spring.datasource.url=jdbc:postgresql://localhost:5432/miniagendamento
spring.datasource.username=postgres
spring.datasource.password=17032006Dt@

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=${PORT:8080}
